# docker-compose.yml
version: '3.8' # La advertencia de 'obsolete' se puede ignorar por ahora

services:
  backend:
    build:
      context: ./backend # Indica dónde está el Dockerfile y el contexto de construcción
      dockerfile: Dockerfile # Nombre del Dockerfile para el backend
    ports:
      - "5001:5001" # Mapea el puerto 5001 del host al puerto 5001 del contenedor
    volumes:
      - ./backend:/app # Monta el directorio local 'backend' en '/app' dentro del contenedor
      - /app/node_modules # Impide que el directorio node_modules local sobreescriba el del contenedor
    environment:
      - NODE_ENV=development # Define el entorno para el backend
    networks:
      - app-network # Asigna el servicio a una red para comunicación interna

  frontend:
    build:
      context: ./frontend # Indica dónde está el Dockerfile y el contexto de construcción
      dockerfile: Dockerfile # Nombre del Dockerfile para el frontend
    ports:
      - "3001:80" # Mapea el puerto 3000 del host al puerto 3000 del contenedor
    volumes:
      - ./frontend:/app # Monta el directorio local 'frontend' en '/app' dentro del contenedor
      - /app/node_modules # Impide que el directorio node_modules local sobreescriba el del contenedor
    environment:
      - NODE_ENV=development # Define el entorno para el frontend
      - REACT_APP_API_URL=http://backend:5001 # ¡CRÍTICO! URL del backend accesible desde el frontend
    depends_on:
      - backend # Asegura que el backend se inicie antes que el frontend
    networks:
      - app-network # Asigna el servicio a una red para comunicación interna

networks:
  app-network: # Define una red personalizada para la comunicación entre servicios
    driver: bridge
