version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NODE_ENV_DB=docker # Para que el backend sepa que la BD está en Docker
    networks:
      - app-network
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args: # <-- ¡CRÍTICO! Pasa REACT_APP_API_URL durante el build del frontend
        - REACT_APP_API_URL=http://backend:5001 # URL del backend DENTRO de la red de Docker
    ports:
      - "3001:80" # Mapea 3001 del host a 80 del contenedor Nginx
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment: # Variables de entorno para el CONTENEDOR en ejecución
      - NODE_ENV=development
      # La variable REACT_APP_API_URL ya fue quemada en el build.
      # No es estrictamente necesario aquí en runtime, pero no causa daño.
    depends_on:
      - backend
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017" # Mapea 27017 del host a 27017 del contenedor Mongo
    volumes:
      - mongodb_data:/data/db # Persistencia de datos de MongoDB
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: # Define el volumen nombrado para MongoDB